sudo: required

language: go

matrix:
  include:
  - go: 1.10.x

before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- dep ensure

cache:
  directories:
  - vendor

script:
- diff -u <(echo -n) <(gofmt -d .)
- go tool vet .
- go test -v -race ./...
