[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/segmentio/ksuid"
  version = "1.0.1"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.6"
